import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils"
import { Navigation } from "@/components/ui/Navigation";
import { Footer } from "@/components/ui/Footer";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Medi Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="" lang="en">
      <body className={`${fontSans.className} flex flex-col min-h-screen`}>
        <Navigation/>
        <main className="flex-grow">{children}</main>
        <Footer/>
      </body>
      
  </html>
  );
}
